all:
	@$(MAKE) -f Makefile_linqueuelst regress cleanall
	@$(MAKE) -f Makefile_sllist2 regress cleanall
	@$(MAKE) -f Makefile_continuations regress cleanall
	@$(MAKE) -f Makefile_threads regress cleanall


